import type { Metadata } from "next";

import "./globals.css";
import Provider from "../../Provider";
import StoreProvider from "@/redux/StoreProvider";
import InitUser from "@/initUser";
import {Toaster} from 'react-hot-toast'
import { CheckCircle, XCircle } from "lucide-react";

export const metadata: Metadata = {
  title: "Full Ecommerce",
  description: "Generated by Next js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="w-full min-h-screen bg-gray-50"
      >
        <Provider>
        <StoreProvider>
        <InitUser/>
        {children}
           <Toaster
      position="top-right"
      reverseOrder={false}
      toastOptions={{
        duration: 3000,
        style: {
          fontWeight: 500,
          borderRadius: "12px",
          padding: "12px 16px",
          boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
          fontSize: "14px",
        },
        success: {
          icon: <CheckCircle className="w-5 h-5 text-blue-500" />,
          style: {
            background: "#eff6ff", 
            color: "#1e3a8a",       
            border: "1px solid #3b82f6",
          },
        },
        error: {
          icon: <XCircle className="w-5 h-5 text-red-500" />,
          style: {
            background: "#fee2e2", 
            color: "#b91c1c",    
            border: "1px solid #ef4444",
          },
        },
        
        
      }}
    />
        </StoreProvider>
        </Provider>
      </body>
    </html>
  );
}
